name: omeeowash
description:
  "Omeeo Wash is a mobile car washing and detailing service in Ghana, offering both
  onsite and mobile cleaning options. This Flutter app lets customers easily book,
  schedule, and manage their car wash services."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  font_awesome_flutter: ^10.7.0
  http: ^1.4.0
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  cloud_functions: ^5.5.2
  firebase_app_check: ^0.3.2+7
  firebase_storage: ^12.4.7
  firebase_database: ^11.3.7
  google_sign_in: ^6.2.1
  google_maps_flutter: ^2.5.0
  push: ^3.3.3
  lottie: ^3.3.1
  flutter_native_splash: ^2.3.5
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.1
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  image_picker: ^1.0.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png" # fallback for older Android & iOS
  adaptive_icon_foreground: "assets/logo.png" # your logo with transparent background
  adaptive_icon_background: "#FFFFFF"
# flutter pub run flutter_launcher_icons:main

flutter_native_splash:
  color: "#000000"
  image: assets/images/omeeo_wash_black_stripes.png
  android_12:
    color: "#FFFFFF"
    image: assets/images/omeeo_wash_black_stripes.png
    icon_background_color: "#FFFFFF"
# flutter pub run flutter_native_splash:create
